DROP TABLE IF EXISTS reset_tokens;
DROP TABLE IF EXISTS email_verifications;
DROP TABLE IF EXISTS bookmarks;
DROP TABLE IF EXISTS user_badges;
DROP TABLE IF EXISTS badges;
DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS materials;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_credentials;